// data.js

// 1. Base de datos para el juego de la SERPIENTE (Frases divididas en palabras)
const snakeMissions = [
    { words: ["I", "can", "swim", "well"], fakes: ["cans", "to swim", "swimming"], note: "Can + base form." },
    { words: ["She", "must", "study", "hard"], fakes: ["musts", "to study", "studying"], note: "Must indicates obligation." },
    { words: ["You", "should", "eat", "now"], fakes: ["shoulds", "to eat", "eating"], note: "Should is for advice." },
    { words: ["It", "might", "rain", "later"], fakes: ["mights", "to rain", "raining"], note: "Might indicates possibility." },
    { words: ["They", "could", "help", "us"], fakes: ["coulds", "to help", "helping"], note: "Could is past ability or polite request." },
    { words: ["We", "may", "leave", "early"], fakes: ["mays", "to leave", "leaving"], note: "May is for formal permission." },
    { words: ["He", "would", "like", "coffee"], fakes: ["woulds", "to like", "liking"], note: "Would + like is a polite desire." },
    { words: ["You", "must", "not", "smoke"], fakes: ["musts", "not to", "smoking"], note: "Must not indicates prohibition." },
    { words: ["Can", "you", "open", "it?"], fakes: ["Cans", "to open", "opening"], note: "Question: Modal + Subject + Verb." },
    { words: ["I", "should", "go", "home"], fakes: ["shoulds", "to go", "going"], note: "Recommendation for oneself." },
    { words: ["She", "can", "speak", "French"], fakes: ["cans", "to speak", "speaking"], note: "Ability in present." },
    { words: ["They", "must", "arrive", "soon"], fakes: ["musts", "to arrive", "arriving"], note: "Logical deduction or obligation." },
    { words: ["It", "could", "be", "true"], fakes: ["coulds", "to be", "being"], note: "Possibility." },
    { words: ["May", "I", "sit", "here?"], fakes: ["Mays", "to sit", "sitting"], note: "Asking for permission." },
    { words: ["We", "shall", "dance", "tonight"], fakes: ["shalls", "to dance", "dancing"], note: "Shall is used for suggestions (formal)." },
    { words: ["He", "might", "know", "her"], fakes: ["mights", "to know", "knowing"], note: "Uncertainty." },
    { words: ["You", "would", "love", "this"], fakes: ["woulds", "to love", "loving"], note: "Hypothetical situation." },
    { words: ["I", "must", "finish", "today"], fakes: ["musts", "to finish", "finishing"], note: "Personal obligation." },
    { words: ["Can", "we", "start", "now?"], fakes: ["Cans", "to start", "starting"], note: "Requesting to begin." },
    { words: ["You", "should", "try", "it"], fakes: ["shoulds", "to try", "trying"], note: "Giving a suggestion." },
    { words: ["They", "can", "run", "fast"], fakes: ["cans", "to run", "running"], note: "Physical ability." },
    { words: ["It", "should", "work", "fine"], fakes: ["shoulds", "to work", "working"], note: "Expectation." },
    { words: ["May", "God", "bless", "you"], fakes: ["Mays", "to bless", "blessing"], note: "Formal wish." },
    { words: ["We", "could", "play", "tennis"], fakes: ["coulds", "to play", "playing"], note: "Suggestion." },
    { words: ["She", "might", "feel", "sick"], fakes: ["mights", "to feel", "feeling"], note: "Possibility regarding health." },
    { words: ["I", "would", "never", "lie"], fakes: ["woulds", "to lie", "lying"], note: "Condition or promise." },
    { words: ["Must", "we", "do", "this?"], fakes: ["Musts", "to do", "doing"], note: "Questioning obligation." },
    { words: ["You", "can", "stay", "here"], fakes: ["cans", "to stay", "staying"], note: "Giving permission." },
    { words: ["It", "may", "take", "time"], fakes: ["mays", "to take", "taking"], note: "Formal possibility." },
    { words: ["He", "should", "be", "careful"], fakes: ["shoulds", "to be", "being"], note: "Advice." },
    { words: ["They", "would", "buy", "it"], fakes: ["woulds", "to buy", "buying"], note: "Hypothetical result." },
    { words: ["Can", "I", "ask", "something?"], fakes: ["Cans", "to ask", "asking"], note: "Permission (informal)." },
    { words: ["We", "must", "keep", "quiet"], fakes: ["musts", "to keep", "keeping"], note: "Strict rule." },
    { words: ["She", "could", "write", "poems"], fakes: ["coulds", "to write", "writing"], note: "Past ability." },
    { words: ["You", "might", "lose", "it"], fakes: ["mights", "to lose", "losing"], note: "Warning of possibility." },
    { words: ["I", "shall", "be", "there"], fakes: ["shalls", "to be", "being"], note: "Future intent (formal)." },
    { words: ["It", "must", "be", "cold"], fakes: ["musts", "to be", "being"], note: "Logical conclusion." },
    { words: ["Would", "you", "mind", "waiting?"], fakes: ["Woulds", "to mind", "minding"], note: "Polite request." },
    { words: ["He", "can", "drive", "trucks"], fakes: ["cans", "to drive", "driving"], note: "Skill." },
    { words: ["We", "should", "protect", "nature"], fakes: ["shoulds", "to protect", "protecting"], note: "Moral obligation." },
    { words: ["May", "I", "come", "in?"], fakes: ["Mays", "to come", "coming"], note: "Formal request." },
    { words: ["She", "would", "help", "everyone"], fakes: ["woulds", "to help", "helping"], note: "Past habit or conditional." },
    { words: ["You", "could", "see", "him"], fakes: ["coulds", "to see", "seeing"], note: "Opportunity." },
    { words: ["They", "might", "need", "money"], fakes: ["mights", "to need", "needing"], note: "Speculation." },
    { words: ["I", "should", "call", "her"], fakes: ["shoulds", "to call", "calling"], note: "Good idea." },
    { words: ["Must", "I", "sign", "here?"], fakes: ["Musts", "to sign", "signing"], note: "Asking about rules." },
    { words: ["Can", "you", "fix", "this?"], fakes: ["Cans", "to fix", "fixing"], note: "Asking for help." },
    { words: ["It", "would", "be", "nice"], fakes: ["woulds", "to be", "being"], note: "Wishing." },
    { words: ["We", "could", "go", "sailing"], fakes: ["coulds", "to go", "going"], note: "Possibility." },
    { words: ["You", "may", "start", "writing"], fakes: ["mays", "to start", "starting"], note: "Permission (exam)." }
];